site_name: Terakoya Cafe Terrace
theme:
  name: material
  language: ja

  nav:
    - Movie:
      - DirectX: Movie/DirectX.md
      - DXR: Movie/DXR.md
      - Unreal Engine: Movie/UE.md
      - Siv3D: Movie/Siv3D.md
      - SRP: Movie/SRP.md
      - GameProgrammingC++: Movie/GP.md
      - OS: Movie/OS.md
      - RL: Movie/RL.md
    - Implementation:
      - 実装: Implementation/Implemantation.md
      - Todo: Implemantation/Todo.md
    - Hobby:
      - Anime: Hobby/Anime.md
      - Movie: Hobby/movie.md
      - Book: Hobby/book.md
      - Trip: Hobby/Trip.md
      - Onsen: Hobby/Onsen.md
    - Dialy:
      - 2026:
        - 1月:
          - 01/01~01/04: Diary/2026/01/2026_0101_0104.md
    - Derive:
      - Optics:
    - Future:
      - 2026: Future/future_2026.md
    - GameStatistics:
      - MHWilds: GameStatistics/MHWilds.md
      - MHRise: GameStatistics/MHRise.md

markdown_extensions:
  - pymdownx.tilde
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
