site_name: Terakoya Cafe Terrace
theme:
  name: material
  language: ja

  nav:
    - Movie:
      - DirectX: Movie/DirectX.md
      - DXR: Movie/DXR.md
      - Unreal Engine: Movie/UE.md
      - Siv3D: Movie/Siv3D.md
      - SRP: Movie/SRP.md
      - GameProgrammingC++: Movie/GP.md
      - OS: Movie/OS.md
      - RL: Movie/RL.md
    - Implementation: Implementation/Implemantation.md
    - Hobby:
      - Anime: Hobby/Anime.md
      - Movie: Hobby/movie.md
      - Book: Hobby/book.md
      - Trip: Hobby/Trip.md
      - Onsen: Hobby/Onsen.md
    - Future:
      - 2026: Future/future_2026.md
    - GameStatistics:
      - MHWilds: GameStatistics/MHWilds.md
      - MHRise: GameStatistics/MHRise.md